# Generated by Django 2.2.1 on 2019-05-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='timpstamp',
            new_name='timestamp',
        ),
    ]
